/*
PE 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Constraints: 10 <= N <= 4 x 10^16
*/
#include <iostream>

int64_t SumFibs(int64_t limit);

int main()
{
  std::cout << SumFibs(10) << std::endl;
  std::cout << SumFibs(90) << std::endl;
  std::cout << SumFibs(4e6) << std::endl;
  std::cout << SumFibs(4e16) << std::endl;
  std::cin.get();
}
